//
//  OCVFSNode.h
//  ownCloudSDK
//
//  Created by Felix Schwarz on 28.04.22.
//  Copyright © 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

#import <Foundation/Foundation.h>
#import "OCVFSTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface OCVFSNode : NSObject

@property(weak,nullable) OCVFSNode *parentNode;

@property(strong,nonatomic) OCVFSNodeID identifier; //!< Internal ID of virtual nodes.
@property(assign) OCVFSNodeType type; //!< The type of VFS node.
@property(assign) BOOL autogeneratedFillNode; //!< YES if this node has been autogenerated to fill a gap in the tree, i.e. if /some/folder is added and /some doesn't exist, the VFS core autogenerates a /some "fill node". Needed primarily for internal housekeeping.

@property(strong) NSString *name; //!< The name of the VFS node.
@property(strong) OCPath path; //!< The virtual path of the VFS node.

@property(strong, nullable) OCLocation *location; //!< The real location of a folder on a server

+ (OCVFSNode *)virtualFolderAtPath:(OCPath)path withName:(NSString *)name location:(OCLocation *)location;

@end

NS_ASSUME_NONNULL_END
