//
// GAAppRole.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GAAppRole.h"

// occgen: type start
@implementation GAAppRole

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GAAppRole *instance = [self new];

	GA_SET(allowedMemberTypes, NSString, NSArray.class);
	GA_MAP(desc, "description", NSString, Nil);
	GA_SET(displayName, NSString, Nil);
	GA_MAP_REQ(identifier, "id", NSString, Nil);

	return (instance);
}

// occgen: struct serialization
- (nullable GAGraphStruct)encodeToGraphStructWithContext:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GA_ENC_INIT
	GA_ENC_ADD(_allowedMemberTypes, "allowedMemberTypes", NO);
	GA_ENC_ADD(_desc, "description", NO);
	GA_ENC_ADD(_displayName, "displayName", NO);
	GA_ENC_ADD(_identifier, "id", YES);
	GA_ENC_RETURN
}

// occgen: type native deserialization
+ (BOOL)supportsSecureCoding
{
	return (YES);
}

- (instancetype)initWithCoder:(NSCoder *)decoder
{
	if ((self = [super init]) != nil)
	{
		_allowedMemberTypes = [decoder decodeObjectOfClasses:[NSSet setWithObjects: NSString.class, NSArray.class, nil] forKey:@"allowedMemberTypes"];
		_desc = [decoder decodeObjectOfClass:NSString.class forKey:@"desc"];
		_displayName = [decoder decodeObjectOfClass:NSString.class forKey:@"displayName"];
		_identifier = [decoder decodeObjectOfClass:NSString.class forKey:@"identifier"];
	}

	return (self);
}

// occgen: type native serialization
- (void)encodeWithCoder:(NSCoder *)coder
{
	[coder encodeObject:_allowedMemberTypes forKey:@"allowedMemberTypes"];
	[coder encodeObject:_desc forKey:@"desc"];
	[coder encodeObject:_displayName forKey:@"displayName"];
	[coder encodeObject:_identifier forKey:@"identifier"];
}

// occgen: type debug description
- (NSString *)description
{
	return ([NSString stringWithFormat:@"<%@: %p%@%@%@%@>", NSStringFromClass(self.class), self, ((_allowedMemberTypes!=nil) ? [NSString stringWithFormat:@", allowedMemberTypes: %@", _allowedMemberTypes] : @""), ((_desc!=nil) ? [NSString stringWithFormat:@", desc: %@", _desc] : @""), ((_displayName!=nil) ? [NSString stringWithFormat:@", displayName: %@", _displayName] : @""), ((_identifier!=nil) ? [NSString stringWithFormat:@", identifier: %@", _identifier] : @"")]);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

