//
// GAAudio.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "GAGraphObject.h"

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface GAAudio : NSObject <GAGraphObject, NSSecureCoding>

// occgen: type properties
@property(strong, nullable) NSString *album; //!< The title of the album for this audio file.
@property(strong, nullable) NSString *albumArtist; //!< The artist named on the album for the audio file.
@property(strong, nullable) NSString *artist; //!< The performing artist for the audio file.
@property(strong, nullable) NSNumber *bitrate; //!< [integer:int64] Bitrate expressed in kbps.
@property(strong, nullable) NSString *composers; //!< The name of the composer of the audio file.
@property(strong, nullable) NSString *copyright; //!< Copyright information for the audio file.
@property(strong, nullable) NSNumber *disc; //!< [integer:int16] The number of the disc this audio file came from.
@property(strong, nullable) NSNumber *discCount; //!< [integer:int16] The total number of discs in this album.
@property(strong, nullable) NSNumber *duration; //!< [integer:int64] Duration of the audio file, expressed in milliseconds
@property(strong, nullable) NSString *genre; //!< The genre of this audio file.
@property(strong, nullable) NSNumber *hasDrm; //!< [boolean] Indicates if the file is protected with digital rights management.
@property(strong, nullable) NSNumber *isVariableBitrate; //!< [boolean] Indicates if the file is encoded with a variable bitrate.
@property(strong, nullable) NSString *title; //!< The title of the audio file.
@property(strong, nullable) NSNumber *track; //!< [integer:int32] The number of the track on the original disc for this audio file.
@property(strong, nullable) NSNumber *trackCount; //!< [integer:int32] The total number of tracks on the original disc for this audio file.
@property(strong, nullable) NSNumber *year; //!< [integer:int32] The year the audio file was recorded.

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

