//
// GADeleted.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "GAGraphObject.h"

// occgen: forward declarations
typedef NSString * GADeletedState;

// occgen: type start {"locked":true}
NS_ASSUME_NONNULL_BEGIN
typedef NSString* GADeletedState NS_TYPED_ENUM;

@interface GADeleted : NSObject <GAGraphObject, NSSecureCoding>

// occgen: type properties { "customPropertyTypes" : { "state" : "GADeletedState" }}
@property(strong, nullable) GADeletedState state; //!< Represents the state of the deleted item.

// occgen: type protected {"locked":true}


// occgen: type end {"locked":true}
@end

extern GADeletedState GADeletedStateTrashed;

NS_ASSUME_NONNULL_END

