//
// GADrive.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GADrive.h"
#import "GAQuota.h"
#import "GAUser.h"
#import "GADriveItem.h"
#import "GAIdentitySet.h"
#import "GAItemReference.h"

// occgen: type start
@implementation GADrive

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GADrive *instance = [self new];

	GA_MAP(identifier, "id", NSString, Nil);
	GA_SET(createdBy, GAIdentitySet, Nil);
	GA_SET(createdDateTime, NSDate, Nil);
	GA_MAP(desc, "description", NSString, Nil);
	GA_SET(eTag, NSString, Nil);
	GA_SET(lastModifiedBy, GAIdentitySet, Nil);
	GA_SET(lastModifiedDateTime, NSDate, Nil);
	GA_SET(name, NSString, Nil);
	GA_SET(parentReference, GAItemReference, Nil);
	GA_SET(webUrl, NSURL, Nil);
	GA_SET(createdByUser, GAUser, Nil);
	GA_SET(lastModifiedByUser, GAUser, Nil);
	GA_SET(driveType, NSString, Nil);
	GA_SET(owner, GAIdentitySet, Nil);
	GA_SET(quota, GAQuota, Nil);
	GA_SET(items, GADriveItem, NSArray.class);
	GA_SET(root, GADriveItem, Nil);
	GA_SET(special, GADriveItem, NSArray.class);

	return (instance);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

