//
// GADriveItem.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GADriveItem.h"
#import "GAUser.h"
#import "GAOpenGraphFile.h"
#import "GAItemReference.h"
#import "GARoot.h"
#import "GATrash.h"
#import "GAFileSystemInfo.h"
#import "GASpecialFolder.h"
#import "GADriveItem.h"
#import "GAImage.h"
#import "GAFolder.h"
#import "GADeleted.h"
#import "GAIdentitySet.h"

// occgen: type start
@implementation GADriveItem

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GADriveItem *instance = [self new];

	GA_MAP(identifier, "id", NSString, Nil);
	GA_SET(createdBy, GAIdentitySet, Nil);
	GA_SET(createdDateTime, NSDate, Nil);
	GA_MAP(desc, "description", NSString, Nil);
	GA_SET(eTag, NSString, Nil);
	GA_SET(lastModifiedBy, GAIdentitySet, Nil);
	GA_SET(lastModifiedDateTime, NSDate, Nil);
	GA_SET(name, NSString, Nil);
	GA_SET(parentReference, GAItemReference, Nil);
	GA_SET(webUrl, NSURL, Nil);
	GA_SET(createdByUser, GAUser, Nil);
	GA_SET(lastModifiedByUser, GAUser, Nil);
	GA_SET(content, NSString, Nil);
	GA_SET(cTag, NSString, Nil);
	GA_SET(deleted, GADeleted, Nil);
	GA_SET(file, GAOpenGraphFile, Nil);
	GA_SET(fileSystemInfo, GAFileSystemInfo, Nil);
	GA_SET(folder, GAFolder, Nil);
	GA_SET(image, GAImage, Nil);
	GA_SET(root, GARoot, Nil);
	GA_SET(trash, GATrash, Nil);
	GA_SET(specialFolder, GASpecialFolder, Nil);
	GA_SET(size, NSNumber, Nil);
	GA_SET(webDavUrl, NSURL, Nil);
	GA_SET(children, GADriveItem, NSArray.class);

	return (instance);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

