//
// GAEducationClass.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2025 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2025, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GAEducationClass.h"
#import "GAUser.h"

// occgen: type start
@implementation GAEducationClass

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GAEducationClass *instance = [self new];

	GA_MAP(identifier, "id", NSString, Nil);
	GA_MAP(desc, "description", NSString, Nil);
	GA_SET(displayName, NSString, Nil);
	GA_SET(members, GAUser, NSArray.class);
// 	GA_SET(members@odata.bind, NSString, NSArray.class);
	GA_SET(classification, NSString, Nil);
	GA_SET(externalId, NSString, Nil);

	return (instance);
}

// occgen: struct serialization
- (nullable GAGraphStruct)encodeToGraphStructWithContext:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GA_ENC_INIT
	GA_ENC_ADD(_identifier, "id", NO);
	GA_ENC_ADD(_desc, "description", NO);
	GA_ENC_ADD(_displayName, "displayName", NO);
	GA_ENC_ADD(_members, "members", NO);
// 	GA_ENC_ADD(_members@odata.bind, "members@odata.bind", NO);
	GA_ENC_ADD(_classification, "classification", NO);
	GA_ENC_ADD(_externalId, "externalId", NO);
	GA_ENC_RETURN
}

// occgen: type native deserialization
+ (BOOL)supportsSecureCoding
{
	return (YES);
}

- (instancetype)initWithCoder:(NSCoder *)decoder
{
	if ((self = [super init]) != nil)
	{
		_identifier = [decoder decodeObjectOfClass:NSString.class forKey:@"identifier"];
		_desc = [decoder decodeObjectOfClass:NSString.class forKey:@"desc"];
		_displayName = [decoder decodeObjectOfClass:NSString.class forKey:@"displayName"];
		_members = [decoder decodeObjectOfClasses:[NSSet setWithObjects: GAUser.class, NSArray.class, nil] forKey:@"members"];
// 		_members@odata.bind = [decoder decodeObjectOfClasses:[NSSet setWithObjects: NSString.class, NSArray.class, nil] forKey:@"members@odata.bind"];
		_classification = [decoder decodeObjectOfClass:NSString.class forKey:@"classification"];
		_externalId = [decoder decodeObjectOfClass:NSString.class forKey:@"externalId"];
	}

	return (self);
}

// occgen: type native serialization
- (void)encodeWithCoder:(NSCoder *)coder
{
	[coder encodeObject:_identifier forKey:@"identifier"];
	[coder encodeObject:_desc forKey:@"desc"];
	[coder encodeObject:_displayName forKey:@"displayName"];
	[coder encodeObject:_members forKey:@"members"];
// 	[coder encodeObject:_members@odata.bind forKey:@"members@odata.bind"];
	[coder encodeObject:_classification forKey:@"classification"];
	[coder encodeObject:_externalId forKey:@"externalId"];
}

// occgen: type debug description
- (NSString *)description
{
	return ([NSString stringWithFormat:@"<%@: %p%@%@%@%@%@%@>", NSStringFromClass(self.class), self, ((_identifier!=nil) ? [NSString stringWithFormat:@", identifier: %@", _identifier] : @""), ((_desc!=nil) ? [NSString stringWithFormat:@", desc: %@", _desc] : @""), ((_displayName!=nil) ? [NSString stringWithFormat:@", displayName: %@", _displayName] : @""), ((_members!=nil) ? [NSString stringWithFormat:@", members: %@", _members] : @""), ((_classification!=nil) ? [NSString stringWithFormat:@", classification: %@", _classification] : @""), ((_externalId!=nil) ? [NSString stringWithFormat:@", externalId: %@", _externalId] : @"")]);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

