//
// GAFolder.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GAFolder.h"
#import "GAFolderView.h"

// occgen: type start
@implementation GAFolder

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GAFolder *instance = [self new];

	GA_SET(childCount, NSNumber, Nil);
	GA_SET(view, GAFolderView, Nil);

	return (instance);
}

// occgen: struct serialization
- (nullable GAGraphStruct)encodeToGraphStructWithContext:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GA_ENC_INIT
	GA_ENC_ADD(_childCount, "childCount", NO);
	GA_ENC_ADD(_view, "view", NO);
	GA_ENC_RETURN
}

// occgen: type native deserialization
+ (BOOL)supportsSecureCoding
{
	return (YES);
}

- (instancetype)initWithCoder:(NSCoder *)decoder
{
	if ((self = [super init]) != nil)
	{
		_childCount = [decoder decodeObjectOfClass:NSNumber.class forKey:@"childCount"];
		_view = [decoder decodeObjectOfClass:GAFolderView.class forKey:@"view"];
	}

	return (self);
}

// occgen: type native serialization
- (void)encodeWithCoder:(NSCoder *)coder
{
	[coder encodeObject:_childCount forKey:@"childCount"];
	[coder encodeObject:_view forKey:@"view"];
}

// occgen: type debug description
- (NSString *)description
{
	return ([NSString stringWithFormat:@"<%@: %p%@%@>", NSStringFromClass(self.class), self, ((_childCount!=nil) ? [NSString stringWithFormat:@", childCount: %@", _childCount] : @""), ((_view!=nil) ? [NSString stringWithFormat:@", view: %@", _view] : @"")]);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

