//
// GAFolderView.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GAFolderView.h"

// occgen: type start
@implementation GAFolderView

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GAFolderView *instance = [self new];

	GA_SET(sortBy, NSString, Nil);
	GA_SET(sortOrder, NSString, Nil);
	GA_SET(viewType, NSString, Nil);

	return (instance);
}

// occgen: type native deserialization
+ (BOOL)supportsSecureCoding
{
	return (YES);
}

- (instancetype)initWithCoder:(NSCoder *)decoder
{
	if ((self = [super init]) != nil)
	{
		_sortBy = [decoder decodeObjectOfClass:NSString.class forKey:@"sortBy"];
		_sortOrder = [decoder decodeObjectOfClass:NSString.class forKey:@"sortOrder"];
		_viewType = [decoder decodeObjectOfClass:NSString.class forKey:@"viewType"];
	}

	return (self);
}

// occgen: type native serialization
- (void)encodeWithCoder:(NSCoder *)coder
{
	[coder encodeObject:_sortBy forKey:@"sortBy"];
	[coder encodeObject:_sortOrder forKey:@"sortOrder"];
	[coder encodeObject:_viewType forKey:@"viewType"];
}

// occgen: type debug description
- (NSString *)description
{
	return ([NSString stringWithFormat:@"<%@: %p%@%@%@>", NSStringFromClass(self.class), self, ((_sortBy!=nil) ? [NSString stringWithFormat:@", sortBy: %@", _sortBy] : @""), ((_sortOrder!=nil) ? [NSString stringWithFormat:@", sortOrder: %@", _sortOrder] : @""), ((_viewType!=nil) ? [NSString stringWithFormat:@", viewType: %@", _viewType] : @"")]);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

