//
// GAGroup.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "GAGraphObject.h"

// occgen: forward declarations
@class GADrive;
@class GADirectoryObject;

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface GAGroup : NSObject <GAGraphObject>

// occgen: type properties {"locked":true}
@property(strong, nullable) NSString *identifier; //!< Read-only.
@property(strong, nullable) NSDate *deletedDateTime; //!< [string:date-time] | pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?([Zz]|[+-][0-9][0-9]:[0-9][0-9])$
@property(strong, nullable) NSDate *createdDateTime; //!< [string:date-time] Timestamp of when the group was created. The value cannot be modified and is automatically populated when the group is created. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Returned by default. Supports $filter (eq, ne, not, ge, le, in). Read-only. | pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
@property(strong, nullable) NSString *desc; //!< An optional description for the group. Returned by default. Supports $filter (eq, ne, not, ge, le, startsWith) and $search.
@property(strong, nullable) NSString *displayName; //!< The display name for the group. This property is required when a group is created and cannot be cleared during updates. Returned by default. Supports $filter (eq, ne, not, ge, le, in, startsWith, and eq on null values), $search, and $orderBy.
@property(strong, nullable) NSDate *expirationDateTime; //!< [string:date-time] Timestamp of when the group is set to expire. The value cannot be modified and is automatically populated when the group is created. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Returned by default. Supports $filter (eq, ne, not, ge, le, in). Read-only. | pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
@property(strong, nullable) NSString *mail; //!< The SMTP address for the group, for example, ''serviceadmins@owncloud.com''. Returned by default. Read-only. Supports $filter (eq, ne, not, ge, le, in, startsWith, and eq on null values).
@property(strong, nullable) NSString *onPremisesDomainName; //!< Contains the on-premises domain FQDN, also called dnsDomainName synchronized from the on-premises directory.
@property(strong, nullable) NSDate *onPremisesLastSyncDateTime; //!< [string:date-time] Indicates the last time at which the group was synced with the on-premises directory.The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Returned by default. Read-only. Supports $filter (eq, ne, not, ge, le, in). | pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
@property(strong, nullable) NSString *onPremisesSamAccountName; //!< Contains the on-premises SAM account name synchronized from the on-premises directory. The property is only populated for customers who are synchronizing their on-premises directory to Azure Active Directory via Azure AD Connect.Returned by default. Supports $filter (eq, ne, not, ge, le, in, startsWith). Read-only.
@property(strong, nullable) NSNumber *onPremisesSyncEnabled; //!< [boolean] true if this group is synced from an on-premises directory; false if this group was originally synced from an on-premises directory but is no longer synced; null if this object has never been synced from an on-premises directory (default). Returned by default. Read-only. Supports $filter (eq, ne, not, in, and eq on null values).
@property(strong, nullable) NSString *preferredLanguage; //!< The preferred language for a group. Should follow ISO 639-1 Code; for example en-US. Returned by default. Supports $filter (eq, ne, not, ge, le, in, startsWith, and eq on null values).
@property(strong, nullable) NSNumber *securityEnabled; //!< [boolean] Specifies whether the group is a security group. Required. Returned by default. Supports $filter (eq, ne, not, in).
@property(strong, nullable) NSString *securityIdentifier; //!< Security identifier of the group, used in Windows scenarios. Returned by default.
@property(strong, nullable) NSString *visibility; //!< Specifies the group join policy and group content visibility for groups. Possible values are: Private, Public, or Hiddenmembership. It can''t be updated later. Other values of visibility can be updated after group creation. Groups assignable to roles are always Private. See group visibility options to learn more. Returned by default. Nullable.
@property(strong, nullable) GADirectoryObject *createdOnBehalfOf; //!< The user (or application) that created the group. NOTE: This is not set if the user is an administrator. Read-only.
@property(strong, nullable) NSArray<GADirectoryObject *> *memberOf; //!< Groups that this group is a member of. HTTP Methods: GET (supported for all groups). Read-only. Nullable. Supports $expand.
@property(strong, nullable) NSArray<GADirectoryObject *> *members; //!< Users and groups that are members of this group. HTTP Methods: GET (supported for all groups), Nullable. Supports $expand.
@property(strong, nullable) NSArray<GADirectoryObject *> *owners; //!< The owners of the group. The owners are a set of non-admin users who are allowed to modify this object. Limited to 100 owners. Nullable. Supports $expand.
@property(strong, nullable) GADrive *drive;
@property(strong, nullable) NSArray<GADrive *> *drives; //!< The group's drives. Read-only.
@property(strong, nullable) NSNumber *isArchived; //!< [boolean]
// @property(strong, nullable) NSArray *'members@odata.bind'; //!< A list of member references to the members to be added. Up to 20 members can be added with a single request

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

