//
// GAGroup.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GAGroup.h"
#import "GADrive.h"
#import "GADirectoryObject.h"

// occgen: type start
@implementation GAGroup

// occgen: type serialization {"locked":true}
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GAGroup *instance = [self new];

	GA_MAP(identifier, "id", NSString, Nil);
	GA_SET(deletedDateTime, NSDate, Nil);
	GA_SET(createdDateTime, NSDate, Nil);
	GA_MAP(desc, "description", NSString, Nil);
	GA_SET(displayName, NSString, Nil);
	GA_SET(expirationDateTime, NSDate, Nil);
	GA_SET(mail, NSString, Nil);
	GA_SET(onPremisesDomainName, NSString, Nil);
	GA_SET(onPremisesLastSyncDateTime, NSDate, Nil);
	GA_SET(onPremisesSamAccountName, NSString, Nil);
	GA_SET(onPremisesSyncEnabled, NSNumber, Nil);
	GA_SET(preferredLanguage, NSString, Nil);
	GA_SET(securityEnabled, NSNumber, Nil);
	GA_SET(securityIdentifier, NSString, Nil);
	GA_SET(visibility, NSString, Nil);
	GA_SET(createdOnBehalfOf, GADirectoryObject, Nil);
	GA_SET(memberOf, GADirectoryObject, NSArray.class);
	GA_SET(members, GADirectoryObject, NSArray.class);
	GA_SET(owners, GADirectoryObject, NSArray.class);
	GA_SET(drive, GADrive, Nil);
	GA_SET(drives, GADrive, NSArray.class);
	GA_SET(isArchived, NSNumber, Nil);
//	GA_SET('members@odata.bind', NSArray, Nil);

	return (instance);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

