//
// GAIdentitySet.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GAIdentitySet.h"
#import "GAIdentity.h"

// occgen: type start
@implementation GAIdentitySet

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GAIdentitySet *instance = [self new];

	GA_SET(application, GAIdentity, Nil);
	GA_SET(device, GAIdentity, Nil);
	GA_SET(user, GAIdentity, Nil);
	GA_SET(group, GAIdentity, Nil);

	return (instance);
}

// occgen: struct serialization
- (nullable GAGraphStruct)encodeToGraphStructWithContext:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GA_ENC_INIT
	GA_ENC_ADD(_application, "application", NO);
	GA_ENC_ADD(_device, "device", NO);
	GA_ENC_ADD(_user, "user", NO);
	GA_ENC_ADD(_group, "group", NO);
	GA_ENC_RETURN
}

// occgen: type native deserialization
+ (BOOL)supportsSecureCoding
{
	return (YES);
}

- (instancetype)initWithCoder:(NSCoder *)decoder
{
	if ((self = [super init]) != nil)
	{
		_application = [decoder decodeObjectOfClass:GAIdentity.class forKey:@"application"];
		_device = [decoder decodeObjectOfClass:GAIdentity.class forKey:@"device"];
		_user = [decoder decodeObjectOfClass:GAIdentity.class forKey:@"user"];
		_group = [decoder decodeObjectOfClass:GAIdentity.class forKey:@"group"];
	}

	return (self);
}

// occgen: type native serialization
- (void)encodeWithCoder:(NSCoder *)coder
{
	[coder encodeObject:_application forKey:@"application"];
	[coder encodeObject:_device forKey:@"device"];
	[coder encodeObject:_user forKey:@"user"];
	[coder encodeObject:_group forKey:@"group"];
}

// occgen: type debug description
- (NSString *)description
{
	return ([NSString stringWithFormat:@"<%@: %p%@%@%@%@>", NSStringFromClass(self.class), self, ((_application!=nil) ? [NSString stringWithFormat:@", application: %@", _application] : @""), ((_device!=nil) ? [NSString stringWithFormat:@", device: %@", _device] : @""), ((_user!=nil) ? [NSString stringWithFormat:@", user: %@", _user] : @""), ((_group!=nil) ? [NSString stringWithFormat:@", group: %@", _group] : @"")]);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

