//
// GAIdentitySet.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "GAGraphObject.h"

// occgen: forward declarations
@class GAIdentity;

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface GAIdentitySet : NSObject <GAGraphObject>

// occgen: type properties
@property(strong, nullable) GAIdentity *application; //!< Optional. The application associated with this action.
@property(strong, nullable) GAIdentity *device; //!< Optional. The device associated with this action.
@property(strong, nullable) GAIdentity *user; //!< Optional. The user associated with this action.

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

