//
// GAItemReference.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "GAGraphObject.h"

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface GAItemReference : NSObject <GAGraphObject, NSSecureCoding>

// occgen: type properties
@property(strong, nullable) NSString *driveId; //!< Unique identifier of the drive instance that contains the item. Read-only.
@property(strong, nullable) NSString *driveType; //!< Identifies the type of drive. See [drive][] resource for values. Read-only.
@property(strong, nullable) NSString *identifier; //!< Unique identifier of the item in the drive. Read-only.
@property(strong, nullable) NSString *name; //!< The name of the item being referenced. Read-only.
@property(strong, nullable) NSString *path; //!< Path that can be used to navigate to the item. Read-only.

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

