//
// GAPasswordProfile.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GAPasswordProfile.h"

// occgen: type start
@implementation GAPasswordProfile

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GAPasswordProfile *instance = [self new];

	GA_SET(forceChangePasswordNextSignIn, NSNumber, Nil);
	GA_SET(password, NSString, Nil);

	return (instance);
}

// occgen: struct serialization
- (nullable GAGraphStruct)encodeToGraphStructWithContext:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GA_ENC_INIT
	GA_ENC_ADD(_forceChangePasswordNextSignIn, "forceChangePasswordNextSignIn", NO);
	GA_ENC_ADD(_password, "password", NO);
	GA_ENC_RETURN
}

// occgen: type native deserialization
+ (BOOL)supportsSecureCoding
{
	return (YES);
}

- (instancetype)initWithCoder:(NSCoder *)decoder
{
	if ((self = [super init]) != nil)
	{
		_forceChangePasswordNextSignIn = [decoder decodeObjectOfClass:NSNumber.class forKey:@"forceChangePasswordNextSignIn"];
		_password = [decoder decodeObjectOfClass:NSString.class forKey:@"password"];
	}

	return (self);
}

// occgen: type native serialization
- (void)encodeWithCoder:(NSCoder *)coder
{
	[coder encodeObject:_forceChangePasswordNextSignIn forKey:@"forceChangePasswordNextSignIn"];
	[coder encodeObject:_password forKey:@"password"];
}

// occgen: type debug description
- (NSString *)description
{
	return ([NSString stringWithFormat:@"<%@: %p%@%@>", NSStringFromClass(self.class), self, ((_forceChangePasswordNextSignIn!=nil) ? [NSString stringWithFormat:@", forceChangePasswordNextSignIn: %@", _forceChangePasswordNextSignIn] : @""), ((_password!=nil) ? [NSString stringWithFormat:@", password: %@", _password] : @"")]);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

