//
// GAPermission.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GAPermission.h"
#import "GAIdentitySet.h"

// occgen: type start
@implementation GAPermission

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GAPermission *instance = [self new];

	GA_SET(grantedTo, GAIdentitySet, NSArray.class);
	GA_SET(roles, NSArray, Nil);

	return (instance);
}

// occgen: type native deserialization
+ (BOOL)supportsSecureCoding
{
	return (YES);
}

- (instancetype)initWithCoder:(NSCoder *)decoder
{
	if ((self = [super init]) != nil)
	{
		_grantedTo = [decoder decodeObjectOfClasses:[NSSet setWithObjects: GAIdentitySet.class, NSArray.class.class, nil] forKey:@"grantedTo"];
		_roles = [decoder decodeObjectOfClass:NSArray.class forKey:@"roles"];
	}

	return (self);
}

// occgen: type native serialization
- (void)encodeWithCoder:(NSCoder *)coder
{
	[coder encodeObject:_grantedTo forKey:@"grantedTo"];
	[coder encodeObject:_roles forKey:@"roles"];
}

// occgen: type debug description
- (NSString *)description
{
	return ([NSString stringWithFormat:@"<%@: %p%@%@>", NSStringFromClass(self.class), self, ((_grantedTo!=nil) ? [NSString stringWithFormat:@", grantedTo: %@", _grantedTo] : @""), ((_roles!=nil) ? [NSString stringWithFormat:@", roles: %@", _roles] : @"")]);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

