//
// GAPermission.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "GAGraphObject.h"

// occgen: forward declarations
@class GAIdentitySet;
@class GASharePointIdentitySet;
@class GASharingInvitation;
@class GASharingLink;

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface GAPermission : NSObject <GAGraphObject, NSSecureCoding>

// occgen: type properties
@property(strong, nullable) NSString *identifier; //!< The unique identifier of the permission among all permissions on the item. Read-only.
@property(strong, nullable) NSNumber *hasPassword; //!< [boolean] |
@property(strong, nullable) NSDate *expirationDateTime; //!< [string:date-time] An optional expiration date which limits the permission in time.
@property(strong, nullable) NSDate *createdDateTime; //!< [string:date-time] An optional creation date. Libregraph only.
@property(strong, nullable) GASharePointIdentitySet *grantedToV2; //!< For user type permissions, the details of the users and applications for this permission. Only part of responses. Use the invitation property when creating shares.
@property(strong, nullable) GASharingLink *link; //!< Provides the link details of the current permission, if it is a link type permissions.
@property(strong, nullable) NSArray<NSString *> *roles;
@property(strong, nullable) NSArray<GAIdentitySet *> *grantedToIdentities; //!< For link type permissions, the details of the identity to whom permission was granted. This could be used to grant access to a an external user that can be identified by email, aka guest accounts.
@property(strong, nullable) NSArray<NSString *> *libreGraphPermissionsActions; //!< Use this to create a permission with custom actions.
@property(strong, nullable) GASharingInvitation *invitation; //!< |

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

