//
// GAPhoto.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "GAGraphObject.h"

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface GAPhoto : NSObject <GAGraphObject, NSSecureCoding>

// occgen: type properties
@property(strong, nullable) NSString *cameraMake; //!< Camera manufacturer. Read-only.
@property(strong, nullable) NSString *cameraModel; //!< Camera model. Read-only.
@property(strong, nullable) NSNumber *exposureDenominator; //!< [number:double] The denominator for the exposure time fraction from the camera. Read-only.
@property(strong, nullable) NSNumber *exposureNumerator; //!< [number:double] The numerator for the exposure time fraction from the camera. Read-only.
@property(strong, nullable) NSNumber *fNumber; //!< [number:double] The F-stop value from the camera. Read-only.
@property(strong, nullable) NSNumber *focalLength; //!< [number:double] The focal length from the camera. Read-only.
@property(strong, nullable) NSNumber *iso; //!< [integer:int32] The ISO value from the camera. Read-only.
@property(strong, nullable) NSNumber *orientation; //!< [integer:int16] The orientation value from the camera. Read-only.
@property(strong, nullable) NSDate *takenDateTime; //!< [string:date-time] Represents the date and time the photo was taken. Read-only. | pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?([Zz]|[+-][0-9][0-9]:[0-9][0-9])$

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

