//
// GARemoteItem.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "GAGraphObject.h"

// occgen: forward declarations
typedef NSString * OCFileETag;
@class GAFileSystemInfo;
@class GAFolder;
@class GAIdentitySet;
@class GAImage;
@class GAItemReference;
@class GAOpenGraphFile;
@class GAPermission;
@class GASpecialFolder;

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface GARemoteItem : NSObject <GAGraphObject, NSSecureCoding>

// occgen: type properties { "customPropertyTypes" : { "eTag" : "OCFileETag" }}
@property(strong, nullable) GAIdentitySet *createdBy;
@property(strong, nullable) NSDate *createdDateTime; //!< [string:date-time] Date and time of item creation. Read-only. | pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
@property(strong, nullable) GAOpenGraphFile *file;
@property(strong, nullable) GAFileSystemInfo *fileSystemInfo;
@property(strong, nullable) GAFolder *folder;
@property(strong, nullable) NSString *driveAlias; //!< The drive alias can be used in clients to make the urls user friendly. Example: 'personal/einstein'. This will be used to resolve to the correct driveID.
@property(strong, nullable) NSString *path; //!< The relative path of the item in relation to its drive root.
@property(strong, nullable) NSString *rootId; //!< Unique identifier for the drive root of this item. Read-only.
@property(strong, nullable) NSString *identifier; //!< Unique identifier for the remote item in its drive. Read-only.
@property(strong, nullable) GAImage *image;
@property(strong, nullable) GAIdentitySet *lastModifiedBy;
@property(strong, nullable) NSDate *lastModifiedDateTime; //!< [string:date-time] Date and time the item was last modified. Read-only. | pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
@property(strong, nullable) NSString *name; //!< Optional. Filename of the remote item. Read-only.
@property(strong, nullable) OCFileETag eTag; //!< ETag for the item. Read-only.
@property(strong, nullable) NSString *cTag; //!< An eTag for the content of the item. This eTag is not changed if only the metadata is changed. Note This property is not returned if the item is a folder. Read-only.
@property(strong, nullable) GAItemReference *parentReference;
@property(strong, nullable) NSArray<GAPermission *> *permissions; //!< The set of permissions for the item. Read-only. Nullable.
@property(strong, nullable) NSNumber *size; //!< [integer:int64] Size of the remote item. Read-only.
@property(strong, nullable) GASpecialFolder *specialFolder;
@property(strong, nullable) NSURL *webDavUrl; //!< DAV compatible URL for the item.
@property(strong, nullable) NSURL *webUrl; //!< URL that displays the resource in the browser. Read-only.

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

