//
// GARemoteItem.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GARemoteItem.h"
#import "GAFileSystemInfo.h"
#import "GAFolder.h"
#import "GAIdentitySet.h"
#import "GAImage.h"
#import "GAItemReference.h"
#import "GAOpenGraphFile.h"
#import "GAShared.h"
#import "GASpecialFolder.h"

// occgen: type start
@implementation GARemoteItem

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GARemoteItem *instance = [self new];

	GA_SET(createdBy, GAIdentitySet, Nil);
	GA_SET(createdDateTime, NSDate, Nil);
	GA_SET(file, GAOpenGraphFile, Nil);
	GA_SET(fileSystemInfo, GAFileSystemInfo, Nil);
	GA_SET(folder, GAFolder, Nil);
	GA_MAP(identifier, "id", NSString, Nil);
	GA_SET(image, GAImage, Nil);
	GA_SET(lastModifiedBy, GAIdentitySet, Nil);
	GA_SET(lastModifiedDateTime, NSDate, Nil);
	GA_SET(name, NSString, Nil);
	GA_SET(eTag, NSString, Nil);
	GA_SET(cTag, NSString, Nil);
	GA_SET(parentReference, GAItemReference, Nil);
	GA_SET(shared, GAShared, Nil);
	GA_SET(size, NSNumber, Nil);
	GA_SET(specialFolder, GASpecialFolder, Nil);
	GA_SET(webDavUrl, NSURL, Nil);
	GA_SET(webUrl, NSURL, Nil);

	return (instance);
}

// occgen: type native deserialization
+ (BOOL)supportsSecureCoding
{
	return (YES);
}

- (instancetype)initWithCoder:(NSCoder *)decoder
{
	if ((self = [super init]) != nil)
	{
		_createdBy = [decoder decodeObjectOfClass:GAIdentitySet.class forKey:@"createdBy"];
		_createdDateTime = [decoder decodeObjectOfClass:NSDate.class forKey:@"createdDateTime"];
		_file = [decoder decodeObjectOfClass:GAOpenGraphFile.class forKey:@"file"];
		_fileSystemInfo = [decoder decodeObjectOfClass:GAFileSystemInfo.class forKey:@"fileSystemInfo"];
		_folder = [decoder decodeObjectOfClass:GAFolder.class forKey:@"folder"];
		_identifier = [decoder decodeObjectOfClass:NSString.class forKey:@"identifier"];
		_image = [decoder decodeObjectOfClass:GAImage.class forKey:@"image"];
		_lastModifiedBy = [decoder decodeObjectOfClass:GAIdentitySet.class forKey:@"lastModifiedBy"];
		_lastModifiedDateTime = [decoder decodeObjectOfClass:NSDate.class forKey:@"lastModifiedDateTime"];
		_name = [decoder decodeObjectOfClass:NSString.class forKey:@"name"];
		_eTag = [decoder decodeObjectOfClass:NSString.class forKey:@"eTag"];
		_cTag = [decoder decodeObjectOfClass:NSString.class forKey:@"cTag"];
		_parentReference = [decoder decodeObjectOfClass:GAItemReference.class forKey:@"parentReference"];
		_shared = [decoder decodeObjectOfClass:GAShared.class forKey:@"shared"];
		_size = [decoder decodeObjectOfClass:NSNumber.class forKey:@"size"];
		_specialFolder = [decoder decodeObjectOfClass:GASpecialFolder.class forKey:@"specialFolder"];
		_webDavUrl = [decoder decodeObjectOfClass:NSURL.class forKey:@"webDavUrl"];
		_webUrl = [decoder decodeObjectOfClass:NSURL.class forKey:@"webUrl"];
	}

	return (self);
}

// occgen: type native serialization
- (void)encodeWithCoder:(NSCoder *)coder
{
	[coder encodeObject:_createdBy forKey:@"createdBy"];
	[coder encodeObject:_createdDateTime forKey:@"createdDateTime"];
	[coder encodeObject:_file forKey:@"file"];
	[coder encodeObject:_fileSystemInfo forKey:@"fileSystemInfo"];
	[coder encodeObject:_folder forKey:@"folder"];
	[coder encodeObject:_identifier forKey:@"identifier"];
	[coder encodeObject:_image forKey:@"image"];
	[coder encodeObject:_lastModifiedBy forKey:@"lastModifiedBy"];
	[coder encodeObject:_lastModifiedDateTime forKey:@"lastModifiedDateTime"];
	[coder encodeObject:_name forKey:@"name"];
	[coder encodeObject:_eTag forKey:@"eTag"];
	[coder encodeObject:_cTag forKey:@"cTag"];
	[coder encodeObject:_parentReference forKey:@"parentReference"];
	[coder encodeObject:_shared forKey:@"shared"];
	[coder encodeObject:_size forKey:@"size"];
	[coder encodeObject:_specialFolder forKey:@"specialFolder"];
	[coder encodeObject:_webDavUrl forKey:@"webDavUrl"];
	[coder encodeObject:_webUrl forKey:@"webUrl"];
}

// occgen: type debug description
- (NSString *)description
{
	return ([NSString stringWithFormat:@"<%@: %p%@%@%@%@%@%@%@%@%@%@%@%@%@%@%@%@%@%@>", NSStringFromClass(self.class), self, ((_createdBy!=nil) ? [NSString stringWithFormat:@", createdBy: %@", _createdBy] : @""), ((_createdDateTime!=nil) ? [NSString stringWithFormat:@", createdDateTime: %@", _createdDateTime] : @""), ((_file!=nil) ? [NSString stringWithFormat:@", file: %@", _file] : @""), ((_fileSystemInfo!=nil) ? [NSString stringWithFormat:@", fileSystemInfo: %@", _fileSystemInfo] : @""), ((_folder!=nil) ? [NSString stringWithFormat:@", folder: %@", _folder] : @""), ((_identifier!=nil) ? [NSString stringWithFormat:@", identifier: %@", _identifier] : @""), ((_image!=nil) ? [NSString stringWithFormat:@", image: %@", _image] : @""), ((_lastModifiedBy!=nil) ? [NSString stringWithFormat:@", lastModifiedBy: %@", _lastModifiedBy] : @""), ((_lastModifiedDateTime!=nil) ? [NSString stringWithFormat:@", lastModifiedDateTime: %@", _lastModifiedDateTime] : @""), ((_name!=nil) ? [NSString stringWithFormat:@", name: %@", _name] : @""), ((_eTag!=nil) ? [NSString stringWithFormat:@", eTag: %@", _eTag] : @""), ((_cTag!=nil) ? [NSString stringWithFormat:@", cTag: %@", _cTag] : @""), ((_parentReference!=nil) ? [NSString stringWithFormat:@", parentReference: %@", _parentReference] : @""), ((_shared!=nil) ? [NSString stringWithFormat:@", shared: %@", _shared] : @""), ((_size!=nil) ? [NSString stringWithFormat:@", size: %@", _size] : @""), ((_specialFolder!=nil) ? [NSString stringWithFormat:@", specialFolder: %@", _specialFolder] : @""), ((_webDavUrl!=nil) ? [NSString stringWithFormat:@", webDavUrl: %@", _webDavUrl] : @""), ((_webUrl!=nil) ? [NSString stringWithFormat:@", webUrl: %@", _webUrl] : @"")]);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

