//
// GAShared.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "GAGraphObject.h"

// occgen: forward declarations
@class GAIdentitySet;

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface GAShared : NSObject <GAGraphObject, NSSecureCoding>

// occgen: type properties
@property(strong, nullable) GAIdentitySet *owner;
@property(strong, nullable) NSString *scope; //!< Indicates the scope of how the item is shared: anonymous, organization, or users. Read-only.
@property(strong, nullable) GAIdentitySet *sharedBy;
@property(strong, nullable) NSDate *sharedDateTime; //!< [string:date-time] The UTC date and time when the item was shared. Read-only. | pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

