//
// GASharingLink.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GASharingLink.h"

// occgen: type start
@implementation GASharingLink

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GASharingLink *instance = [self new];

	GA_SET(type, NSString, Nil);
	GA_SET(preventsDownload, NSNumber, Nil);
	GA_SET(webUrl, NSURL, Nil);
	GA_MAP(libreGraphDisplayName, "@libre.graph.displayName", NSString, Nil);
	GA_MAP(libreGraphQuickLink, "@libre.graph.quickLink", NSNumber, Nil);

	return (instance);
}

// occgen: struct serialization
- (nullable GAGraphStruct)encodeToGraphStructWithContext:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GA_ENC_INIT
	GA_ENC_ADD(_type, "type", NO);
	GA_ENC_ADD(_preventsDownload, "preventsDownload", NO);
	GA_ENC_ADD(_webUrl, "webUrl", NO);
	GA_ENC_ADD(_libreGraphDisplayName, "@libre.graph.displayName", NO);
	GA_ENC_ADD(_libreGraphQuickLink, "@libre.graph.quickLink", NO);
	GA_ENC_RETURN
}

// occgen: type native deserialization
+ (BOOL)supportsSecureCoding
{
	return (YES);
}

- (instancetype)initWithCoder:(NSCoder *)decoder
{
	if ((self = [super init]) != nil)
	{
		_type = [decoder decodeObjectOfClass:NSString.class forKey:@"type"];
		_preventsDownload = [decoder decodeObjectOfClass:NSNumber.class forKey:@"preventsDownload"];
		_webUrl = [decoder decodeObjectOfClass:NSURL.class forKey:@"webUrl"];
		_libreGraphDisplayName = [decoder decodeObjectOfClass:NSString.class forKey:@"libreGraphDisplayName"];
		_libreGraphQuickLink = [decoder decodeObjectOfClass:NSNumber.class forKey:@"libreGraphQuickLink"];
	}

	return (self);
}

// occgen: type native serialization
- (void)encodeWithCoder:(NSCoder *)coder
{
	[coder encodeObject:_type forKey:@"type"];
	[coder encodeObject:_preventsDownload forKey:@"preventsDownload"];
	[coder encodeObject:_webUrl forKey:@"webUrl"];
	[coder encodeObject:_libreGraphDisplayName forKey:@"libreGraphDisplayName"];
	[coder encodeObject:_libreGraphQuickLink forKey:@"libreGraphQuickLink"];
}

// occgen: type debug description
- (NSString *)description
{
	return ([NSString stringWithFormat:@"<%@: %p%@%@%@%@%@>", NSStringFromClass(self.class), self, ((_type!=nil) ? [NSString stringWithFormat:@", type: %@", _type] : @""), ((_preventsDownload!=nil) ? [NSString stringWithFormat:@", preventsDownload: %@", _preventsDownload] : @""), ((_webUrl!=nil) ? [NSString stringWithFormat:@", webUrl: %@", _webUrl] : @""), ((_libreGraphDisplayName!=nil) ? [NSString stringWithFormat:@", libreGraphDisplayName: %@", _libreGraphDisplayName] : @""), ((_libreGraphQuickLink!=nil) ? [NSString stringWithFormat:@", libreGraphQuickLink: %@", _libreGraphQuickLink] : @"")]);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

