//
// GASharingLink.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "GAGraphObject.h"
#import "GASharingLinkType.h"

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface GASharingLink : NSObject <GAGraphObject, NSSecureCoding>

// occgen: type properties
@property(strong, nullable) GASharingLinkType type;
@property(strong, nullable) NSNumber *preventsDownload; //!< [boolean] If `true` then the user can only use this link to view the item on the web, and cannot use it to download the contents of the item.
@property(strong, nullable) NSURL *webUrl; //!< A URL that opens the item in the browser on the website.
@property(strong, nullable) NSString *libreGraphDisplayName; //!< Provides a user-visible display name of the link. Optional. Libregraph only.
@property(strong, nullable) NSNumber *libreGraphQuickLink; //!< [boolean] The quicklink property can be assigned to only one link per resource. A quicklink can be used in the clients to provide a one-click copy to clipboard action. Optional. Libregraph only.

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

