//
// GASharingLinkType.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GASharingLinkType.h"

// occgen: type start
GASharingLinkType GASharingLinkTypeInternal = @"internal";
GASharingLinkType GASharingLinkTypeView = @"view";
GASharingLinkType GASharingLinkTypeUpload = @"upload";
GASharingLinkType GASharingLinkTypeEdit = @"edit";
GASharingLinkType GASharingLinkTypeCreateOnly = @"createOnly";
GASharingLinkType GASharingLinkTypeBlocksDownload = @"blocksDownload";

// occgen: type protected {"locked":true}

