//
// GAThumbnailSet.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "GAGraphObject.h"

// occgen: forward declarations
@class GAThumbnail;

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface GAThumbnailSet : NSObject <GAGraphObject, NSSecureCoding>

// occgen: type properties
@property(strong, nullable) NSString *identifier; //!< The ID within the item. Read-only.
@property(strong, nullable) GAThumbnail *large; //!< A 1920x1920 scaled thumbnail.
@property(strong, nullable) GAThumbnail *medium; //!< A 176x176 scaled thumbnail.
@property(strong, nullable) GAThumbnail *small; //!< A 48x48 cropped thumbnail.
@property(strong, nullable) GAThumbnail *source; //!< A custom thumbnail image or the original image used to generate other thumbnails.

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

