//
// GATrash.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GATrash.h"
#import "GAIdentitySet.h"

// occgen: type start
@implementation GATrash

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GATrash *instance = [self new];

	GA_SET(trashedBy, GAIdentitySet, Nil);
	GA_SET(trashedDateTime, NSDate, Nil);

	return (instance);
}

// occgen: type native deserialization
+ (BOOL)supportsSecureCoding
{
	return (YES);
}

- (instancetype)initWithCoder:(NSCoder *)decoder
{
	if ((self = [super init]) != nil)
	{
		_trashedBy = [decoder decodeObjectOfClass:GAIdentitySet.class forKey:@"trashedBy"];
		_trashedDateTime = [decoder decodeObjectOfClass:NSDate.class forKey:@"trashedDateTime"];
	}

	return (self);
}

// occgen: type native serialization
- (void)encodeWithCoder:(NSCoder *)coder
{
	[coder encodeObject:_trashedBy forKey:@"trashedBy"];
	[coder encodeObject:_trashedDateTime forKey:@"trashedDateTime"];
}

// occgen: type debug description
- (NSString *)description
{
	return ([NSString stringWithFormat:@"<%@: %p%@%@>", NSStringFromClass(self.class), self, ((_trashedBy!=nil) ? [NSString stringWithFormat:@", trashedBy: %@", _trashedBy] : @""), ((_trashedDateTime!=nil) ? [NSString stringWithFormat:@", trashedDateTime: %@", _trashedDateTime] : @"")]);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

