//
// GAUnifiedRoleDefinition.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes {"locked":true}
#import <Foundation/Foundation.h>
#import "GAGraphObject.h"
#import "OCShareTypes.h"

// occgen: forward declarations {"locked":true}
@class GAUnifiedRolePermission;
@class OCShareRole;

// occgen: type start {"locked":true}
NS_ASSUME_NONNULL_BEGIN
@interface GAUnifiedRoleDefinition : NSObject <GAGraphObject, NSSecureCoding>
{
	OCShareRole *_role;
}

// occgen: type properties { "customPropertyTypes" : { "identifier" : "OCShareRoleID" }}
@property(strong, nullable) NSString *desc; //!< The description for the unifiedRoleDefinition.
@property(strong, nullable) NSString *displayName; //!< The display name for the unifiedRoleDefinition. Required. Supports $filter (`eq`, `in`).
@property(strong, nullable) OCShareRoleID identifier; //!< The unique identifier for the role definition. Key, not nullable, Read-only. Inherited from entity. Supports $filter (`eq`, `in`).
@property(strong, nullable) NSArray<GAUnifiedRolePermission *> *rolePermissions; //!< List of permissions included in the role.
@property(strong, nullable) NSNumber *libreGraphWeight; //!< [integer] |

// occgen: type protected {"locked":true}
@property(strong, nullable, nonatomic) OCShareRole *role;

// occgen: type end
@end
NS_ASSUME_NONNULL_END

