//
// GAUnifiedRolePermission.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2024 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2024, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GAUnifiedRolePermission.h"

// occgen: type start
@implementation GAUnifiedRolePermission

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GAUnifiedRolePermission *instance = [self new];

	GA_SET(allowedResourceActions, NSString, NSArray.class);
	GA_SET(condition, NSString, Nil);

	return (instance);
}

// occgen: struct serialization
- (nullable GAGraphStruct)encodeToGraphStructWithContext:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GA_ENC_INIT
	GA_ENC_ADD(_allowedResourceActions, "allowedResourceActions", NO);
	GA_ENC_ADD(_condition, "condition", NO);
	GA_ENC_RETURN
}

// occgen: type native deserialization
+ (BOOL)supportsSecureCoding
{
	return (YES);
}

- (instancetype)initWithCoder:(NSCoder *)decoder
{
	if ((self = [super init]) != nil)
	{
		_allowedResourceActions = [decoder decodeObjectOfClasses:[NSSet setWithObjects: NSString.class, NSArray.class, nil] forKey:@"allowedResourceActions"];
		_condition = [decoder decodeObjectOfClass:NSString.class forKey:@"condition"];
	}

	return (self);
}

// occgen: type native serialization
- (void)encodeWithCoder:(NSCoder *)coder
{
	[coder encodeObject:_allowedResourceActions forKey:@"allowedResourceActions"];
	[coder encodeObject:_condition forKey:@"condition"];
}

// occgen: type debug description
- (NSString *)description
{
	return ([NSString stringWithFormat:@"<%@: %p%@%@>", NSStringFromClass(self.class), self, ((_allowedResourceActions!=nil) ? [NSString stringWithFormat:@", allowedResourceActions: %@", _allowedResourceActions] : @""), ((_condition!=nil) ? [NSString stringWithFormat:@", condition: %@", _condition] : @"")]);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

