//
// GAUser.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "GAUser.h"
#import "GADrive.h"
#import "GAPasswordProfile.h"

// occgen: type start
@implementation GAUser

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(GAGraphData)structure context:(nullable GAGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	GAUser *instance = [self new];

	GA_MAP(identifier, "id", NSString, Nil);
	GA_SET(deletedDateTime, NSDate, Nil);
	GA_SET(accountEnabled, NSNumber, Nil);
	GA_SET(businessPhones, NSArray, Nil);
	GA_SET(city, NSString, Nil);
	GA_SET(companyName, NSString, Nil);
	GA_SET(country, NSString, Nil);
	GA_SET(createdDateTime, NSDate, Nil);
	GA_SET(department, NSString, Nil);
	GA_SET(displayName, NSString, Nil);
	GA_SET(faxNumber, NSString, Nil);
	GA_SET(givenName, NSString, Nil);
	GA_SET(lastPasswordChangeDateTime, NSDate, Nil);
	GA_SET(legalAgeGroupClassification, NSString, Nil);
	GA_SET(mail, NSString, Nil);
	GA_SET(mailNickname, NSString, Nil);
	GA_SET(mobilePhone, NSString, Nil);
	GA_SET(onPremisesDistinguishedName, NSString, Nil);
	GA_SET(onPremisesDomainName, NSString, Nil);
	GA_SET(onPremisesImmutableId, NSString, Nil);
	GA_SET(onPremisesSyncEnabled, NSNumber, Nil);
	GA_SET(onPremisesLastSyncDateTime, NSDate, Nil);
	GA_SET(onPremisesSamAccountName, NSString, Nil);
	GA_SET(onPremisesUserPrincipalName, NSString, Nil);
	GA_SET(officeLocation, NSString, Nil);
	GA_SET(passwordProfile, GAPasswordProfile, Nil);
	GA_SET(postalCode, NSString, Nil);
	GA_SET(preferredLanguage, NSString, Nil);
	GA_SET(state, NSString, Nil);
	GA_SET(streetAddress, NSString, Nil);
	GA_SET(surname, NSString, Nil);
	GA_SET(usageLocation, NSString, Nil);
	GA_SET(userPrincipalName, NSString, Nil);
	GA_SET(userType, NSString, Nil);
	GA_SET(aboutMe, NSString, Nil);
	GA_SET(birthday, NSDate, Nil);
	GA_SET(preferredName, NSString, Nil);
	GA_SET(drive, GADrive, Nil);
	GA_SET(drives, GADrive, NSArray.class);

	return (instance);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

