//
// OCGDriveItem.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "OCGraphObject.h"

// occgen: forward declarations
@class OCGIdentitySet;
@class OCGDriveItem;
@class OCGUser;
@class OCGDeleted;
@class OCGFileSystemInfo;
@class OCGFolder;
@class OCGOpenGraphFile;
@class OCGSpecialFolder;
@class OCGImage;
@class OCGTrash;
@class OCGItemReference;
@class OCGRoot;

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface OCGDriveItem : NSObject <OCGraphObject>

// occgen: type properties
@property(strong, nullable) NSString *identifier; //!< Read-only.
@property(strong, nullable) OCGIdentitySet *createdBy; //!< Identity of the user, device, or application which created the item. Read-only.
@property(strong, nullable) NSDate *createdDateTime; //!< [string:date-time] Date and time of item creation. Read-only. | pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?([Zz]|[+-][0-9][0-9]:[0-9][0-9])$
@property(strong, nullable) NSString *desc; //!< Provides a user-visible description of the item. Optional.
@property(strong, nullable) NSString *eTag; //!< ETag for the item. Read-only.
@property(strong, nullable) OCGIdentitySet *lastModifiedBy; //!< Identity of the user, device, and application which last modified the item. Read-only.
@property(strong, nullable) NSDate *lastModifiedDateTime; //!< [string:date-time] Date and time the item was last modified. Read-only. | pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?([Zz]|[+-][0-9][0-9]:[0-9][0-9])$
@property(strong, nullable) NSString *name; //!< The name of the item. Read-write.
@property(strong, nullable) OCGItemReference *parentReference; //!< Parent information, if the item has a parent. Read-write.
@property(strong, nullable) NSURL *webUrl; //!< URL that displays the resource in the browser. Read-only.
@property(strong, nullable) OCGUser *createdByUser; //!< Identity of the user who created the item. Read-only.
@property(strong, nullable) OCGUser *lastModifiedByUser; //!< Identity of the user who last modified the item. Read-only.
@property(strong, nullable) NSString *content; //!< [string:base64url] The content stream, if the item represents a file.
@property(strong, nullable) NSString *cTag; //!< An eTag for the content of the item. This eTag is not changed if only the metadata is changed. Note This property is not returned if the item is a folder. Read-only.
@property(strong, nullable) OCGDeleted *deleted;
@property(strong, nullable) OCGOpenGraphFile *file;
@property(strong, nullable) OCGFileSystemInfo *fileSystemInfo;
@property(strong, nullable) OCGFolder *folder;
@property(strong, nullable) OCGImage *image;
@property(strong, nullable) OCGRoot *root;
@property(strong, nullable) OCGTrash *trash;
@property(strong, nullable) OCGSpecialFolder *specialFolder;
@property(strong, nullable) NSNumber *size; //!< [integer:int64] Size of the item in bytes. Read-only.
@property(strong, nullable) NSURL *webDavUrl; //!< WebDAV compatible URL for the item. Read-only.
@property(strong, nullable) NSArray<OCGDriveItem *> *children; //!< Collection containing Item objects for the immediate children of Item. Only items representing folders have children. Read-only. Nullable.

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

