//
// OCGDrive.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "OCGDrive.h"
#import "OCGUser.h"
#import "OCGQuota.h"
#import "OCGDriveItem.h"
#import "OCGIdentitySet.h"
#import "OCGItemReference.h"

// occgen: type start
@implementation OCGDrive

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(OCGraphData)structure context:(nullable OCGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	OCGDrive *instance = [self new];

	OCG_MAP(identifier, "id", NSString, Nil);
	OCG_SET(createdBy, OCGIdentitySet, Nil);
	OCG_SET(createdDateTime, NSDate, Nil);
	OCG_MAP(desc, "description", NSString, Nil);
	OCG_SET(eTag, NSString, Nil);
	OCG_SET(lastModifiedBy, OCGIdentitySet, Nil);
	OCG_SET(lastModifiedDateTime, NSDate, Nil);
	OCG_SET(name, NSString, Nil);
	OCG_SET(parentReference, OCGItemReference, Nil);
	OCG_SET(webUrl, NSURL, Nil);
	OCG_SET(createdByUser, OCGUser, Nil);
	OCG_SET(lastModifiedByUser, OCGUser, Nil);
	OCG_SET(driveType, NSString, Nil);
	OCG_SET(owner, OCGIdentitySet, Nil);
	OCG_SET(quota, OCGQuota, Nil);
	OCG_SET(items, OCGDriveItem, NSArray.class);
	OCG_SET(root, OCGDriveItem, Nil);
	OCG_SET(special, OCGDriveItem, NSArray.class);

	return (instance);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

