//
// OCGDrive.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "OCGraphObject.h"

// occgen: forward declarations
@class OCGUser;
@class OCGQuota;
@class OCGDriveItem;
@class OCGIdentitySet;
@class OCGItemReference;

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface OCGDrive : NSObject <OCGraphObject>

// occgen: type properties
@property(strong, nullable) NSString *identifier; //!< Read-only.
@property(strong, nullable) OCGIdentitySet *createdBy; //!< Identity of the user, device, or application which created the item. Read-only.
@property(strong, nullable) NSDate *createdDateTime; //!< [string:date-time] Date and time of item creation. Read-only. | pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?([Zz]|[+-][0-9][0-9]:[0-9][0-9])$
@property(strong, nullable) NSString *desc; //!< Provides a user-visible description of the item. Optional.
@property(strong, nullable) NSString *eTag; //!< ETag for the item. Read-only.
@property(strong, nullable) OCGIdentitySet *lastModifiedBy; //!< Identity of the user, device, and application which last modified the item. Read-only.
@property(strong, nullable) NSDate *lastModifiedDateTime; //!< [string:date-time] Date and time the item was last modified. Read-only. | pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?([Zz]|[+-][0-9][0-9]:[0-9][0-9])$
@property(strong, nullable) NSString *name; //!< The name of the item. Read-write.
@property(strong, nullable) OCGItemReference *parentReference; //!< Parent information, if the item has a parent. Read-write.
@property(strong, nullable) NSURL *webUrl; //!< URL that displays the resource in the browser. Read-only.
@property(strong, nullable) OCGUser *createdByUser; //!< Identity of the user who created the item. Read-only.
@property(strong, nullable) OCGUser *lastModifiedByUser; //!< Identity of the user who last modified the item. Read-only.
@property(strong, nullable) NSString *driveType; //!< Describes the type of drive represented by this resource. Values are "personal" for users home spaces, "project" or "share". Read-only.
@property(strong, nullable) OCGIdentitySet *owner;
@property(strong, nullable) OCGQuota *quota;
@property(strong, nullable) NSArray<OCGDriveItem *> *items; //!< All items contained in the drive. Read-only. Nullable.
@property(strong, nullable) OCGDriveItem *root;
@property(strong, nullable) NSArray<OCGDriveItem *> *special; //!< A collection of special drive resources.

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

