//
// OCGDriveItem.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "OCGDriveItem.h"
#import "OCGIdentitySet.h"
#import "OCGDriveItem.h"
#import "OCGUser.h"
#import "OCGDeleted.h"
#import "OCGFileSystemInfo.h"
#import "OCGFolder.h"
#import "OCGOpenGraphFile.h"
#import "OCGSpecialFolder.h"
#import "OCGImage.h"
#import "OCGTrash.h"
#import "OCGItemReference.h"
#import "OCGRoot.h"

// occgen: type start
@implementation OCGDriveItem

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(OCGraphData)structure context:(nullable OCGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	OCGDriveItem *instance = [self new];

	OCG_MAP(identifier, "id", NSString, Nil);
	OCG_SET(createdBy, OCGIdentitySet, Nil);
	OCG_SET(createdDateTime, NSDate, Nil);
	OCG_MAP(desc, "description", NSString, Nil);
	OCG_SET(eTag, NSString, Nil);
	OCG_SET(lastModifiedBy, OCGIdentitySet, Nil);
	OCG_SET(lastModifiedDateTime, NSDate, Nil);
	OCG_SET(name, NSString, Nil);
	OCG_SET(parentReference, OCGItemReference, Nil);
	OCG_SET(webUrl, NSURL, Nil);
	OCG_SET(createdByUser, OCGUser, Nil);
	OCG_SET(lastModifiedByUser, OCGUser, Nil);
	OCG_SET(content, NSString, Nil);
	OCG_SET(cTag, NSString, Nil);
	OCG_SET(deleted, OCGDeleted, Nil);
	OCG_SET(file, OCGOpenGraphFile, Nil);
	OCG_SET(fileSystemInfo, OCGFileSystemInfo, Nil);
	OCG_SET(folder, OCGFolder, Nil);
	OCG_SET(image, OCGImage, Nil);
	OCG_SET(root, OCGRoot, Nil);
	OCG_SET(trash, OCGTrash, Nil);
	OCG_SET(specialFolder, OCGSpecialFolder, Nil);
	OCG_SET(size, NSNumber, Nil);
	OCG_SET(webDavUrl, NSURL, Nil);
	OCG_SET(children, OCGDriveItem, NSArray.class);

	return (instance);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

