//
// OCGGroup.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "OCGGroup.h"
#import "OCGDrive.h"
#import "OCGDirectoryObject.h"

// occgen: type start
@implementation OCGGroup

// occgen: type serialization { "locked" : true }
+ (nullable instancetype)decodeGraphData:(OCGraphData)structure context:(nullable OCGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	OCGGroup *instance = [self new];

	OCG_MAP(identifier, "id", NSString, Nil);
	OCG_SET(deletedDateTime, NSDate, Nil);
	OCG_SET(createdDateTime, NSDate, Nil);
	OCG_MAP(desc, "description", NSString, Nil);
	OCG_SET(displayName, NSString, Nil);
	OCG_SET(expirationDateTime, NSDate, Nil);
	OCG_SET(mail, NSString, Nil);
	OCG_SET(onPremisesDomainName, NSString, Nil);
	OCG_SET(onPremisesLastSyncDateTime, NSDate, Nil);
	OCG_SET(onPremisesSamAccountName, NSString, Nil);
	OCG_SET(onPremisesSyncEnabled, NSNumber, Nil);
	OCG_SET(preferredLanguage, NSString, Nil);
	OCG_SET(securityEnabled, NSNumber, Nil);
	OCG_SET(securityIdentifier, NSString, Nil);
	OCG_SET(visibility, NSString, Nil);
	OCG_SET(createdOnBehalfOf, OCGDirectoryObject, Nil);
	OCG_SET(memberOf, OCGDirectoryObject, NSArray.class);
	OCG_SET(members, OCGDirectoryObject, NSArray.class);
	OCG_SET(owners, OCGDirectoryObject, NSArray.class);
	OCG_SET(drive, OCGDrive, Nil);
	OCG_SET(drives, OCGDrive, NSArray.class);
	OCG_SET(isArchived, NSNumber, Nil);
//	OCG_SET('members@odata.bind', NSArray, Nil);

	return (instance);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

