//
// OCGItemReference.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "OCGItemReference.h"

// occgen: type start
@implementation OCGItemReference

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(OCGraphData)structure context:(nullable OCGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	OCGItemReference *instance = [self new];

	OCG_SET(driveId, NSString, Nil);
	OCG_SET(driveType, NSString, Nil);
	OCG_MAP(identifier, "id", NSString, Nil);
	OCG_SET(name, NSString, Nil);
	OCG_SET(path, NSString, Nil);
	OCG_SET(shareId, NSString, Nil);

	return (instance);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

