//
// OCGQuota.h
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import <Foundation/Foundation.h>
#import "OCGraphObject.h"

// occgen: type start
NS_ASSUME_NONNULL_BEGIN
@interface OCGQuota : NSObject <OCGraphObject>

// occgen: type properties
@property(strong, nullable) NSNumber *deleted; //!< [integer:int64] Total space consumed by files in the recycle bin, in bytes. Read-only.
@property(strong, nullable) NSNumber *remaining; //!< [integer:int64] Total space remaining before reaching the quota limit, in bytes. Read-only.
@property(strong, nullable) NSString *state; //!< Enumeration value that indicates the state of the storage space. Read-only.
@property(strong, nullable) NSNumber *total; //!< [integer:int64] Total allowed storage space, in bytes. Read-only.
@property(strong, nullable) NSNumber *used; //!< [integer:int64] Total space used, in bytes. Read-only.

// occgen: type protected {"locked":true}


// occgen: type end
@end
NS_ASSUME_NONNULL_END

