//
// OCGUser.m
// Autogenerated / Managed by ocapigen
// Copyright (C) 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

// occgen: includes
#import "OCGUser.h"
#import "OCGDrive.h"
#import "OCGPasswordProfile.h"

// occgen: type start
@implementation OCGUser

// occgen: type serialization
+ (nullable instancetype)decodeGraphData:(OCGraphData)structure context:(nullable OCGraphContext *)context error:(NSError * _Nullable * _Nullable)outError
{
	OCGUser *instance = [self new];

	OCG_MAP(identifier, "id", NSString, Nil);
	OCG_SET(deletedDateTime, NSDate, Nil);
	OCG_SET(accountEnabled, NSNumber, Nil);
	OCG_SET(businessPhones, NSArray, Nil);
	OCG_SET(city, NSString, Nil);
	OCG_SET(companyName, NSString, Nil);
	OCG_SET(country, NSString, Nil);
	OCG_SET(createdDateTime, NSDate, Nil);
	OCG_SET(department, NSString, Nil);
	OCG_SET(displayName, NSString, Nil);
	OCG_SET(faxNumber, NSString, Nil);
	OCG_SET(givenName, NSString, Nil);
	OCG_SET(lastPasswordChangeDateTime, NSDate, Nil);
	OCG_SET(legalAgeGroupClassification, NSString, Nil);
	OCG_SET(mail, NSString, Nil);
	OCG_SET(mailNickname, NSString, Nil);
	OCG_SET(mobilePhone, NSString, Nil);
	OCG_SET(onPremisesDistinguishedName, NSString, Nil);
	OCG_SET(onPremisesDomainName, NSString, Nil);
	OCG_SET(onPremisesImmutableId, NSString, Nil);
	OCG_SET(onPremisesSyncEnabled, NSNumber, Nil);
	OCG_SET(onPremisesLastSyncDateTime, NSDate, Nil);
	OCG_SET(onPremisesSamAccountName, NSString, Nil);
	OCG_SET(onPremisesUserPrincipalName, NSString, Nil);
	OCG_SET(officeLocation, NSString, Nil);
	OCG_SET(passwordProfile, OCGPasswordProfile, Nil);
	OCG_SET(postalCode, NSString, Nil);
	OCG_SET(preferredLanguage, NSString, Nil);
	OCG_SET(state, NSString, Nil);
	OCG_SET(streetAddress, NSString, Nil);
	OCG_SET(surname, NSString, Nil);
	OCG_SET(usageLocation, NSString, Nil);
	OCG_SET(userPrincipalName, NSString, Nil);
	OCG_SET(userType, NSString, Nil);
	OCG_SET(aboutMe, NSString, Nil);
	OCG_SET(birthday, NSDate, Nil);
	OCG_SET(preferredName, NSString, Nil);
	OCG_SET(drive, OCGDrive, Nil);
	OCG_SET(drives, OCGDrive, NSArray.class);

	return (instance);
}

// occgen: type protected {"locked":true}


// occgen: type end
@end

