name: "Push source language to Transifex"

on:
  push:
    branches:
      - master

jobs:
  push-translations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: l10n-format
        shell: bash
        run: |
          beautifyJSON() {
            jq --sort-keys 'walk(if type == "object" then del(."th_TH", ."pt_PT", ."pt_BR", ."nn_NO", ."nb_NO", ."en_GB") else . end)' $1 >$1.tmp
            mv $1.tmp $1
          }
          beautifyJSON "ownCloudSDK/Resources/Localizable.xcstrings"
          beautifyJSON "ownCloudUI/Resources/Localizable.xcstrings"

      - name: l10n-push-source
        uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TX_TOKEN }}
          args: push -s --skip
